SELECT
    id,
    proposal_id,
    submitted_by_user_id,
    issuer_name,
    contact_name,
    contact_email,
    issuer_website,
    issuer_country,
    asset_name,
    asset_type_id,
    description,
    target_raise,
    currency,
    maturity_date,
    expected_yield_bps,
    redemption_summary,
    valuation_source,
    document_urls,
    token_symbol,
    max_supply,
    subscription_price,
    redemption_price,
    self_service_purchase_enabled,
    metadata_hash,
    slug,
    image_url,
    market_segment,
    suggested_internal_tags,
    source_urls,
    status,
    review_notes,
    reviewed_by_user_id,
    reviewed_at,
    deployed_by_user_id,
    deployed_at,
    deployed_asset_address,
    deployment_tx_hash,
    created_at,
    updated_at
FROM asset_requests
WHERE ($1::TEXT IS NULL OR status = $1)
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
