use chrono::{DateTime, NaiveDate, Utc};
use sqlx::FromRow;
use uuid::Uuid;

#[derive(Debug, Clone, FromRow)]
pub struct AssetRequestRecord {
    pub id: Uuid,
    pub proposal_id: i64,
    pub submitted_by_user_id: Uuid,
    pub issuer_name: String,
    pub contact_name: String,
    pub contact_email: String,
    pub issuer_website: Option<String>,
    pub issuer_country: Option<String>,
    pub asset_name: String,
    pub asset_type_id: String,
    pub description: String,
    pub target_raise: Option<String>,
    pub currency: Option<String>,
    pub maturity_date: Option<NaiveDate>,
    pub expected_yield_bps: Option<i32>,
    pub redemption_summary: Option<String>,
    pub valuation_source: Option<String>,
    pub document_urls: Vec<String>,
    pub token_symbol: String,
    pub max_supply: String,
    pub subscription_price: String,
    pub redemption_price: String,
    pub self_service_purchase_enabled: bool,
    pub metadata_hash: Option<String>,
    pub slug: Option<String>,
    pub image_url: Option<String>,
    pub market_segment: Option<String>,
    pub suggested_internal_tags: Vec<String>,
    pub source_urls: Vec<String>,
    pub status: String,
    pub review_notes: Option<String>,
    pub reviewed_by_user_id: Option<Uuid>,
    pub reviewed_at: Option<DateTime<Utc>>,
    pub deployed_by_user_id: Option<Uuid>,
    pub deployed_at: Option<DateTime<Utc>>,
    pub deployed_asset_address: Option<String>,
    pub deployment_tx_hash: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone)]
pub struct NewAssetRequestRecord {
    pub submitted_by_user_id: Uuid,
    pub issuer_name: String,
    pub contact_name: String,
    pub contact_email: String,
    pub issuer_website: Option<String>,
    pub issuer_country: Option<String>,
    pub asset_name: String,
    pub asset_type_id: String,
    pub description: String,
    pub target_raise: Option<String>,
    pub currency: Option<String>,
    pub maturity_date: Option<NaiveDate>,
    pub expected_yield_bps: Option<i32>,
    pub redemption_summary: Option<String>,
    pub valuation_source: Option<String>,
    pub document_urls: Vec<String>,
    pub token_symbol: String,
    pub max_supply: String,
    pub subscription_price: String,
    pub redemption_price: String,
    pub self_service_purchase_enabled: bool,
    pub metadata_hash: Option<String>,
    pub slug: Option<String>,
    pub image_url: Option<String>,
    pub market_segment: Option<String>,
    pub suggested_internal_tags: Vec<String>,
    pub source_urls: Vec<String>,
}
