CREATE TABLE IF NOT EXISTS asset_requests (
    id UUID PRIMARY KEY,
    proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 300000),
    submitted_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    issuer_name TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    issuer_website TEXT,
    issuer_country TEXT,
    asset_name TEXT NOT NULL,
    asset_type_id TEXT NOT NULL,
    description TEXT NOT NULL,
    target_raise TEXT,
    currency TEXT,
    maturity_date DATE,
    expected_yield_bps INTEGER CHECK (expected_yield_bps IS NULL OR expected_yield_bps >= 0),
    redemption_summary TEXT,
    valuation_source TEXT,
    document_urls TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    token_symbol TEXT NOT NULL,
    max_supply TEXT NOT NULL,
    subscription_price TEXT NOT NULL,
    redemption_price TEXT NOT NULL,
    self_service_purchase_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_hash TEXT,
    slug TEXT,
    image_url TEXT,
    market_segment TEXT,
    suggested_internal_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    source_urls TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (
        status IN ('submitted', 'under_review', 'approved', 'rejected', 'deployed')
    ),
    review_notes TEXT,
    reviewed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    deployed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    deployed_at TIMESTAMPTZ,
    deployed_asset_address TEXT,
    deployment_tx_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (proposal_id)
);

CREATE INDEX IF NOT EXISTS asset_requests_submitted_by_user_id_created_at_idx
ON asset_requests (submitted_by_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS asset_requests_status_created_at_idx
ON asset_requests (status, created_at DESC);

CREATE INDEX IF NOT EXISTS asset_requests_reviewed_by_user_id_idx
ON asset_requests (reviewed_by_user_id);

CREATE INDEX IF NOT EXISTS asset_requests_deployed_by_user_id_idx
ON asset_requests (deployed_by_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS asset_requests_deployed_asset_address_uidx
ON asset_requests (deployed_asset_address)
WHERE deployed_asset_address IS NOT NULL;
