INSERT INTO assets (
    asset_address,
    proposal_id,
    asset_type_id,
    name,
    symbol,
    max_supply,
    total_supply,
    asset_state,
    asset_state_label,
    controllable,
    self_service_purchase_enabled,
    price_per_token,
    redemption_price_per_token,
    treasury_address,
    compliance_registry_address,
    payment_token_address,
    metadata_hash,
    holder_count,
    total_pending_redemptions,
    created_by_user_id,
    updated_by_user_id,
    last_tx_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
)
ON CONFLICT (asset_address) DO UPDATE
SET
    proposal_id = EXCLUDED.proposal_id,
    asset_type_id = EXCLUDED.asset_type_id,
    name = EXCLUDED.name,
    symbol = EXCLUDED.symbol,
    max_supply = EXCLUDED.max_supply,
    total_supply = EXCLUDED.total_supply,
    asset_state = EXCLUDED.asset_state,
    asset_state_label = EXCLUDED.asset_state_label,
    controllable = EXCLUDED.controllable,
    self_service_purchase_enabled = EXCLUDED.self_service_purchase_enabled,
    price_per_token = EXCLUDED.price_per_token,
    redemption_price_per_token = EXCLUDED.redemption_price_per_token,
    treasury_address = EXCLUDED.treasury_address,
    compliance_registry_address = EXCLUDED.compliance_registry_address,
    payment_token_address = EXCLUDED.payment_token_address,
    metadata_hash = EXCLUDED.metadata_hash,
    holder_count = EXCLUDED.holder_count,
    total_pending_redemptions = EXCLUDED.total_pending_redemptions,
    created_by_user_id = COALESCE(assets.created_by_user_id, EXCLUDED.created_by_user_id),
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    last_tx_hash = COALESCE(EXCLUDED.last_tx_hash, assets.last_tx_hash),
    updated_at = NOW()
RETURNING
    asset_address,
    proposal_id,
    asset_type_id,
    name,
    symbol,
    max_supply,
    total_supply,
    asset_state,
    asset_state_label,
    controllable,
    self_service_purchase_enabled,
    price_per_token,
    redemption_price_per_token,
    treasury_address,
    compliance_registry_address,
    payment_token_address,
    metadata_hash,
    holder_count,
    total_pending_redemptions,
    created_by_user_id,
    updated_by_user_id,
    last_tx_hash,
    created_at,
    updated_at
